version: "3.9"

services:
  app:
    build:
      context: .
      args:
        APP_USER_ID: ${APP_USER_ID}
    image: ecommerce:1.0.0
    container_name: ecommerce_app
    env_file:
      - .env
    ports:
      - "8080:8080"
    tty: true
    entrypoint: ["/home/spring/app/entrypoint.sh"]
    command: ["mvnw", "spring-boot:run"]
    volumes:
      - .:/home/spring/app:cached
      - ~/.ssh:/home/spring/.ssh
      - ./mvnw:/usr/local/bin/mvnw
      - ./.m2:/home/spring/.m2

  database:
    image: mysql:8.0
    container_name: ecommerce_database
    hostname: ecommerce_database_host
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
