spring:
  datasource:
    url: jdbc:mysql://ecommerce_database_host:3306/dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: spring_boot
    password: spring_boot_password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
