spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  mvc:
    log-request-details: true
springdoc:
  swagger-ui:
    path: /swagger-ui
